export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';

export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIE_SUCCESS = 'LOAD_MOVIE_SUCCESS';

export const SET_CURRENT_MOVIE_DETAILS = 'SET_CURRENT_MOVIE_DETAILS';
