export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';

export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIE_SUCCESS = 'LOAD_MOVIE_SUCCESS';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_QUERY = 'SEARCH_MOVIE_QUERY';
export const TYPPING_TIMEOUT = 'TYPPING_TIMEOUT';

export const SET_CURRENT_TMDB_MOVIE_DETAILS = 'SET_CURRENT_TMDB_MOVIE_DETAILS';
export const CLEAR_CURRENT_TMDB_MOVIE_DETAILS = 'CLEAR_CURRENT_TMDB_MOVIE_DETAILS';

export const SAVE_TMDB_MOVIE_SUCCESS = 'SAVE_TMDB_MOVIE_SUCCESS';
export const DELETE_TMDB_MOVIE_SUCCESS = 'DELETE_TMDB_MOVIE_SUCCESS';

export const SET_MOVIE_STATUS = 'SET_MOVIE_STATUS';
